
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbCommonPoolConfig TbCommonPoolConfig {get; }
    public TbConditionConfig TbConditionConfig {get; }
    public TbItemConfig TbItemConfig {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbCommonPoolConfig = new TbCommonPoolConfig(loader("tbcommonpoolconfig"));
        TbConditionConfig = new TbConditionConfig(loader("tbconditionconfig"));
        TbItemConfig = new TbItemConfig(loader("tbitemconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCommonPoolConfig.ResolveRef(this);
        TbConditionConfig.ResolveRef(this);
        TbItemConfig.ResolveRef(this);
    }
}

}
